//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediGrids.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class BloqueHorario
    {
        public int id_bloque { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora_inicio { get; set; }
        public System.TimeSpan hora_fin { get; set; }
        public string motivo { get; set; }
        public int id_terapeuta { get; set; }
    
        public virtual Terapeuta Terapeuta { get; set; }
    }
}
