//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediGrids.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int id_cita { get; set; }
        public System.DateTime fecha { get; set; }
        public System.TimeSpan hora_inicio { get; set; }
        public System.TimeSpan hora_fin { get; set; }
        public string estado { get; set; }
        public string motivo_cancelacion { get; set; }
        public int id_paciente { get; set; }
        public int id_terapeuta { get; set; }
        public int id_terapia { get; set; }
        public int id_categoria { get; set; }
    
        public virtual CategoriaClinica CategoriaClinica { get; set; }
        public virtual Paciente Paciente { get; set; }
        public virtual Terapeuta Terapeuta { get; set; }
        public virtual TipoTerapia TipoTerapia { get; set; }
    }
}
