//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediGrids.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ejercicio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ejercicio()
        {
            this.PacienteEjercicio = new HashSet<PacienteEjercicio>();
        }
    
        public int id_ejercicio { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string objetivo { get; set; }
        public string dificultad { get; set; }
        public string video_url { get; set; }
        public int id_terapia { get; set; }
        public int id_categoria { get; set; }
        public int creado_por { get; set; }
        public bool activo { get; set; }
    
        public virtual CategoriaClinica CategoriaClinica { get; set; }
        public virtual Terapeuta Terapeuta { get; set; }
        public virtual TipoTerapia TipoTerapia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PacienteEjercicio> PacienteEjercicio { get; set; }
    }
}
