//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediGrids.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ejercicio
    {
        public int id_ejercicio { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string objetivo { get; set; }
        public string dificultad { get; set; }
        public string video_url { get; set; }
        public int id_terapia { get; set; }
        public int id_categoria { get; set; }
        public int creado_por { get; set; }
    
        public virtual CategoriaClinica CategoriaClinica { get; set; }
        public virtual Terapeuta Terapeuta { get; set; }
        public virtual TipoTerapia TipoTerapia { get; set; }
    }
}
