//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediGrids.EntityFramework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CategoriaClinica> CategoriaClinica { get; set; }
        public virtual DbSet<Ejercicio> Ejercicio { get; set; }
        public virtual DbSet<Paciente> Paciente { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Terapeuta> Terapeuta { get; set; }
        public virtual DbSet<TipoTerapia> TipoTerapia { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
