//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediGrids.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class PacienteEjercicio
    {
        public int id_paciente { get; set; }
        public int id_ejercicio { get; set; }
        public Nullable<System.DateTime> fecha_asignacion { get; set; }
        public string estado { get; set; }
    
        public virtual Ejercicio Ejercicio { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
