//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediGrids.EntityFramework
{
    using System;
    using System.Collections.Generic;

    public partial class PacienteEjercicio
    {
        public int id_paciente { get; set; }
        public int id_ejercicio { get; set; }
        public Nullable<System.DateTime> fecha_asignacion { get; set; }
        public string estado { get; set; }

        public virtual Paciente Paciente { get; set; }
        public virtual Ejercicio Ejercicio { get; set; }
    }
}
