//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MediGrids.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terapeuta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Terapeuta()
        {
            this.Ejercicio = new HashSet<Ejercicio>();
            this.BloqueHorario = new HashSet<BloqueHorario>();
            this.Cita = new HashSet<Cita>();
            this.HorarioTerapeuta = new HashSet<HorarioTerapeuta>();
        }
    
        public int id_terapeuta { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public Nullable<bool> activo { get; set; }
        public Nullable<int> id_categoria { get; set; }
    
        public virtual CategoriaClinica CategoriaClinica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ejercicio> Ejercicio { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BloqueHorario> BloqueHorario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cita> Cita { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HorarioTerapeuta> HorarioTerapeuta { get; set; }
    }
}
